// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Webapp.DB.Models;

namespace Webapp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Webapp.DB.Models.TestTableRecord", b =>
                {
                    b.Property<int>("TestTableRecordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Information");

                    b.HasKey("TestTableRecordId");

                    b.ToTable("TestTableRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
